import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import solc from "solc";
import ganache from "ganache";
import { BrowserProvider, ContractFactory, keccak256, toUtf8Bytes } from "ethers";
const source=await readFile("contracts/SANADCredential.sol","utf8");
const input={language:"Solidity",sources:{"SANADCredential.sol":{content:source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:"shanghai",outputSelection:{"*":{"*":["abi","evm.bytecode.object"]}}}};
const compiled=JSON.parse(solc.compile(JSON.stringify(input)));
assert.equal(compiled.errors?.filter(e=>e.severity==="error").length||0,0,compiled.errors?.map(e=>e.formattedMessage).join("\n"));
const {abi,evm}=compiled.contracts["SANADCredential.sol"].SANADCredential;
const chain=ganache.provider({logging:{quiet:true},chain:{hardfork:"shanghai"}});
const provider=new BrowserProvider(chain);const issuer=await provider.getSigner(0),outsider=await provider.getSigner(1);
const contract=await new ContractFactory(abi,`0x${evm.bytecode.object}`,issuer).deploy();await contract.waitForDeployment();
const id=keccak256(toUtf8Bytes("opaque-id")),hash=keccak256(toUtf8Bytes("fictional-claim"));
await assert.rejects(contract.connect(outsider).issue.staticCall(id,hash));
await (await contract.issue(id,hash)).wait();
let status=await contract.status(id);assert.equal(status[0],hash);assert.equal(status[1],await issuer.getAddress());assert.equal(status[3],false);
await assert.rejects(contract.issue.staticCall(id,hash));
await assert.rejects(contract.connect(outsider).revoke.staticCall(id));
await (await contract.revoke(id)).wait();status=await contract.status(id);assert.equal(status[3],true);
await assert.rejects(contract.revoke.staticCall(id));
console.log("Contract checks passed: issuer-only issue/revoke, immutable hash, duplicate rejection and revocation.");
